export const storeKeys = {
  OBSERVER: 'OBSERVER',
  HORIZONTAL_SCROLL_PCT: 'HORIZONTAL_SCROLL_PCT',
  HORIZONTAL_SCROLLER_OFFSET: 'HORIZONTAL_SCROLLER_OFFSET',
  FIXED_HEIGHT_TRANSITION_PCT: 'FIXED_HEIGHT_TRANSITION_PCT',
  SCROLL_LOCK: 'SCROLL_LOCK',
  SCROLL_SNAPS: 'SCROLL_SNAPS',
  SCROLL_POSITION: 'SCROLL_POSITION',
  SECTION_TOP_SCROLLER_OFFSET: 'SECTION_TOP_SCROLLER_OFFSET',
  GALLERY_IMAGES_LOADED: 'GALLERY_IMAGES_LOADED',
};